Bump transformers and stop at <= 4.44.0
Use >= 4.38.0 because that is the sentence-transformers min anyway.
Add <= 4.44.0 because 4.44.0 breaks our tests with errors like this:
   RuntimeError: The expanded size of the tensor (22) must match the existing size (30) at non-singleton dimension 2.  Target sizes: [4, 22, 22].  Tensor sizes: [4, 1, 30]

Signed-off-by: Mark Sturdevant <mark.sturdevant@ibm.com>